- hosts: localhost
  vars:
    namespace: enmasse-system
    multitenant: true
    enable_rbac: true
    service_catalog: true
    keycloak_admin_password: 
    keycloak_http_url: 
    authentication_services:
      - standard
  roles:
    - enmasse
